---
title: "class_exercise"
format: html
editor: visual
embed-resources: true
---

## Challenge 1
```{r}
library(tidyverse)
library(reticulate)
library(vegabrite)
library(dplyr)
library(jsonlite)
library(mosaic)
```
```{python}
import pandas as pd
import altair as alt
```

```{r}
mailing <- fromJSON("https://calvin-data304.netlify.app/data/swd-lets-practice-ex-2-13.json")
# Wrangling:
mailing_wrangled <- mailing|>
  separate(Date, into = c("quarter", "year"), sep = "-")|>
  mutate(quarter = parse_number(quarter),
         year = parse_number(year),
         date_str = paste0(year, "-", 3* quarter -2, "-01"),
         date = lubridate::ymd(date_str),
         `Net Completion Rate` = `Response Rate` * `Completion Rate`)
# convert to long format
mailing_wrangled <-mailing_wrangled|>
  pivot_longer(matches("Rate"),
               names_to = "Rate Type",
               values_to = "Rate Values")|>
  filter(`Rate Type`!= "Completion Rate")
```
```{r}
mailing_wrangled|>
  vl_chart()|>
  vl_add_data(mailing_wrangled)|>
  vl_mark_line()|>
  vl_encode_x("date:T")|>
  vl_encode_y("Rate Values:Q")|>
  vl_encode_color("Rate Type:N")
```

```{r}
mailing_wrangled|>
  vl_chart()|>
  vl_add_data(mailing_wrangled)|>
  vl_mark_line()|>
  vl_encode_x("date:T")|>
  vl_encode_y("Rate Values:Q")|>
  vl_encode_color("Rate Type:N")

```








